/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utc.creator;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import pojo.Subscription;
import static utc.creator.processor.inputProc;
import static utc.creator.processor.listWriter;
import static utc.creator.processor.outputClaimGen;
import static utc.creator.processor.outputMemGen;

/**
 *
 * @author U55369
 */
public class MainUi extends javax.swing.JFrame {

    /**
     * Creates new form MainUi
     */
    String inputFile;
    String outputFolder;

    public MainUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        folderSelectLabel = new javax.swing.JLabel();
        inputSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputFileLabel = new javax.swing.JTextArea();
        progress = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UTC Gen");
        setLocation(new java.awt.Point(600, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        folderSelectLabel.setText("Selected file : ");

        inputSelect.setText("Select File");
        inputSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSelectActionPerformed(evt);
            }
        });

        inputFileLabel.setEditable(false);
        inputFileLabel.setColumns(20);
        inputFileLabel.setRows(5);
        jScrollPane1.setViewportView(inputFileLabel);

        progress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress.setText("Progress");

        generate.setText("Generate ");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        jButton1.setText("Open Output Folder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(generate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(folderSelectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(inputSelect)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addComponent(progress)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSelectActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(fc.getFileSystemView().getParentDirectory(new File("C:\\")));
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("CSV Files", "csv"));
        fc.showOpenDialog(this);

        if (fc.getSelectedFile() != null) {

            inputFileLabel.setText(fc.getSelectedFile().getAbsolutePath());
            inputFile = fc.getSelectedFile().getAbsolutePath();
            outputFolder = fc.getSelectedFile().getParent();

        }
    }//GEN-LAST:event_inputSelectActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        if (inputFile == null) {

            JOptionPane.showMessageDialog(null, " Please Select Input File and Try Agian ", " Select Input File ", JOptionPane.ERROR_MESSAGE);

        } else {

            try {
                progress.setText("Input Processing ");
                ArrayList<Subscription> list = inputProc(new File(inputFile));
                //System.out.println("Input Processing completed");
                progress.setText("Input Processing completed");

                progress.setText("Claims Tab writing");

                listWriter(outputClaimGen(list), new File(outputFolder + "\\" + new File(inputFile).getName().split("\\.")[0] + " - Claims Tab.csv"));
                progress.setText("Claims Tab writing completed");

                //System.out.println("claim write complete");
                progress.setText("Member Tab writing");

                listWriter(outputMemGen(list), new File(outputFolder + "\\" + new File(inputFile).getName().split("\\.")[0] + " - Members Tab.csv"));
                progress.setText("Member Tab writing Completed");

                progress.setText("Finished");

            } catch (ArrayIndexOutOfBoundsException e) {
             e.printStackTrace();
                       
                JOptionPane.showMessageDialog(null, "Please verify the input CSV file ", " Oops ... Something went wrong !!! ", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, " Oops ... Something went wrong !!! ", JOptionPane.ERROR_MESSAGE);
            }

        }

       // System.out.println("mem write complete");

    }//GEN-LAST:event_generateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (inputFile == null) {

                JOptionPane.showMessageDialog(null, " Please Select Input File and Try Agian ", " Select Input File ", JOptionPane.ERROR_MESSAGE);

            } else {
                Desktop.getDesktop().open(new File(outputFolder));
            }
        } catch (IOException ex) {
            Logger.getLogger(MainUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel folderSelectLabel;
    private javax.swing.JButton generate;
    private javax.swing.JTextArea inputFileLabel;
    private javax.swing.JButton inputSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel progress;
    // End of variables declaration//GEN-END:variables
}
